### ISSUE TITLE
git clone not runs

### ISSUE THREAD

**Issue by ppKrauss** [grossvogel/huffman-coding-php#1]
`php tests.php`

PHP Fatal error:  require_once(): Failed opening required 'bit-util-php/bitstream.php' (include_path='.:/usr/share/php') in /home/peter/sandbox/huffman-coding-php/huffmancoding.php on line 2

**Comment by grossvogel** [comment]
Most likely, your `bit-util-php/` folder is empty because it's a submodule, and the default `git clone` does not pull in submodules. You should be able to download the submodule by running `git submodule update --init --recursive` from inside the repo, or you could use the `--recursive` flag during the initial `git clone`.

Here's a StackOverflow answer for more info: http://stackoverflow.com/a/4438292/14957

**Comment by ppKrauss** [comment]
Hi @grossvogel,  thanks! 

You need to copy/paste explain to your README.
